(Get-ADGroupMember 6700-sg-org-orkkb).name > C:\Temp\1.txt
(Get-ADGroupMember 6700-sg-org-gaokb).name >> C:\Temp\1.txt
(Get-ADGroupMember 6700-sg-org-orksb).name >> C:\Temp\1.txt
(Get-ADGroupMember 6700-sg-org-buh).name >> C:\Temp\1.txt
(Get-ADGroupMember 6700-sg-org-contr).name >> C:\Temp\1.txt
(Get-ADGroupMember 6700-sg-org-oper).name >> C:\Temp\1.txt
(Get-ADGroupMember 6700-sg-org-dolgi).name >> C:\Temp\1.txt
(Get-ADGroupMember 6700-sg-org-kass).name >> C:\Temp\1.txt
(Get-ADGroupMember 6700-sg-org-rasch).name >> C:\Temp\1.txt
(Get-ADGroupMember 6700-sg-org-orkmmb).name >> C:\Temp\1.txt
(Get-ADGroupMember 6700-sg-org-oaommb).name >> C:\Temp\1.txt
(Get-ADGroupMember 6700-sg-org-ur).name >> C:\Temp\1.txt